import { 
    MatButtonModule,
    MatIconModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatTableModule,
    MatToolbarModule,
    MatPaginatorModule, 
    MatRadioModule,
    MatSnackBarModule,
    MatCardModule,
    MatInputModule,
    MatCommonModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDialogModule,
    MatExpansionModule,
    MatGridListModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSortModule,
    MatTabsModule,
    MatTooltipModule,
  } from "@angular/material";
import {NgModule} from "@angular/core";

const MAT_MODULES = [
  MatButtonModule,
  MatIconModule,
  MatDatepickerModule,
  MatFormFieldModule,
  MatTableModule,
  MatToolbarModule,
  MatPaginatorModule, 
  MatRadioModule,
  MatSnackBarModule,
  MatCardModule,
  MatInputModule,
  MatCommonModule,
  MatAutocompleteModule,
  MatButtonToggleModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDialogModule,
  MatExpansionModule,
  MatGridListModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSortModule,
  MatTabsModule,
  MatTooltipModule
]

@NgModule({
  imports: MAT_MODULES,
  exports: MAT_MODULES
})

export class MaterialModule {}
